const Eventdata = 
[
  
    {
      id: 1,
      category: "Food & Drink",
      status: "Paid",
      description: "Join us for a culinary journey showcasing the finest cuisines from around the world. Indulge in a night of gastronomic delights, fine wine, and exquisite desserts.",
      date: "20 Apr",
      day: "Wed",
      time: "6:00 PM - 10:00 PM",
      venue: "Grand Plaza Hotel",
      location: "789 MG Road",
      city: "Delhi",
      host: "Delhi Food Festival",
      title: "International Food Expo",
      image: "Images/food&drink.png"
    },
    {
      id: 2,
      category: "Charity & Causes",
      status: "Free",
      description: "Join us in supporting a noble cause to provide education to underprivileged children. Your contribution can make a significant difference in their lives.",
      date: "25 May",
      day: "Sat",
      time: "10:00 AM - 2:00 PM",
      venue: "City Community Center",
      location: "456 Hill Road",
      city: "Mumbai",
      host: "Mumbai Education Foundation",
      title: "Education Drive",
      image: "Images/charity.png"
    },
    {
      id: 3,
      category: "Business",
      status: "Paid",
      description: "Join industry leaders for insightful discussions and networking opportunities at the Annual Business Summit. Gain valuable insights to drive your business forward.",
      date: "10 Aug",
      day: "Fri",
      time: "9:00 AM - 5:00 PM",
      venue: "Convention Center",
      location: "101 Business Road",
      city: "Pune",
      host: "Pune Chamber of Commerce",
      title: "Annual Business Summit",
      image: "Images/business.png"
    },
    {
      id: 4,
      category: "Startups",
      status: "Free",
      description: "Calling all aspiring entrepreneurs! Attend our startup boot camp and learn essential skills to launch your own business. Get inspired by success stories and expert advice.",
      date: "5 Jul",
      day: "Sat",
      time: "11:00 AM - 4:00 PM",
      venue: "Innovation Hub",
      location: "789 Tech Street",
      city: "Hyderabad",
      host: "Hyderabad Startup Network",
      title: "Startup Boot Camp",
      image: "Images/startup.png"
    },
    {
      id: 5,
      category: "Workshops",
      status: "Paid",
      description: "Unleash your creativity with our hands-on pottery workshop. Learn pottery techniques from experienced artisans and create your own masterpiece.",
      date: "15 Sep",
      day: "Sat",
      time: "2:00 PM - 6:00 PM",
      venue: "Art Studio",
      location: "456 Clay Avenue",
      city: "Chennai",
      host: "Chennai Art Society",
      title: "Pottery Workshop",
      image: "Images/workshop.png"
    },
    {
      id: 6,
      category: "Music",
      status: "Paid",
      description: "Experience an evening of soulful melodies by renowned musicians at our Jazz Night. Sit back, relax, and let the music transport you to another world.",
      date: "18 Jun",
      day: "Fri",
      time: "7:00 PM - 11:00 PM",
      venue: "Harmony Hall",
      location: "101 Jazz Street",
      city: "Mumbai",
      host: "Mumbai Music Society",
      title: "Jazz Night",
      image: "Images/music1.png"
    },
    {
      id: 7,
      category: "Art",
      status: "Free",
      description: "Join us for an art exhibition featuring works by emerging artists. Experience a diverse range of artistic expressions and discover new talents.",
      date: "30 Jul",
      day: "Sat",
      time: "10:00 AM - 4:00 PM",
      venue: "Art Gallery",
      location: "789 Art Avenue",
      city: "Delhi",
      host: "Delhi Art Association",
      title: "Emerging Artists Exhibition",
      image: "Images/art.png"
    },
    {
      id: 8,
      category: "Hobbies",
      status: "Free",
      description: "Calling all photography enthusiasts! Join us for a photo walk through the scenic landscapes of the city. Capture breathtaking moments and learn new techniques.",
      date: "12 Oct",
      day: "Sun",
      time: "8:00 AM - 11:00 AM",
      venue: "City Park",
      location: "456 Photography Lane",
      city: "Bangalore",
      host: "Bangalore Photography Club",
      title: "Photo Walk",
      image: "Images/hobbies.png"
    },
    {
      id: 9,
      category: "Food & Drink",
      status: "Paid",
      description: "Join us for a wine tasting event featuring a selection of fine wines from around the world. Learn about wine varieties and flavor profiles from expert sommeliers.",
      date: "7 Nov",
      day: "Sat",
      time: "4:00 PM - 8:00 PM",
      venue: "Wine Bar",
      location: "101 Vineyard Road",
      city: "Mumbai",
      host: "Mumbai Wine Club",
      title: "Wine Tasting Experience",
      image: "Images/food&drink.png"
    },
    {
      id: 10,
      category: "Charity & Causes",
      status: "Free",
      description: "Join us in supporting environmental conservation efforts by participating in a beach cleanup drive. Together, we can make a positive impact on our planet.",
      date: "20 Sep",
      day: "Sat",
      time: "9:00 AM - 12:00 PM",
      venue: "Beach",
      location: "456 Ocean Avenue",
      city: "Goa",
      host: "Goa Environmental Society",
      title: "Beach Cleanup Drive",
      image: "Images/charity.png"
    },
    {
      id: 11,
      category: "Business",
      status: "Paid",
      description: "Expand your professional network and gain valuable insights at our Networking Breakfast. Connect with industry professionals and explore collaboration opportunities.",
      date: "15 Oct",
      day: "Fri",
      time: "8:00 AM - 10:00 AM",
      venue: "Business Center",
      location: "789 Networking Street",
      city: "Delhi",
      host: "Delhi Business Network",
      title: "Networking Breakfast",
      image: "Images/business.png"
    },
    {
      id: 12,
      category: "Startups",
      status: "Free",
      description: "Join us for a panel discussion featuring successful startup founders sharing their entrepreneurial journey. Gain valuable insights and inspiration for your own venture.",
      date: "3 Nov",
      day: "Wed",
      time: "6:00 PM - 8:00 PM",
      venue: "Startup Hub",
      location: "101 Innovation Avenue",
      city: "Pune",
      host: "Pune Startup Forum",
      title: "Startup Founders Panel",
      image: "Images/startup.png"
    },
    {
      id: 13,
      category: "Workshops",
      status: "Paid",
      description: "Unlock your creative potential with our painting workshop. Learn fundamental painting techniques and unleash your inner artist.",
      date: "10 Sep",
      day: "Tue",
      time: "3:00 PM - 7:00 PM",
      venue: "Art Studio",
      location: "456 Canvas Lane",
      city: "Chennai",
      host: "Chennai Creative Collective",
      title: "Painting Workshop",
      image: "Images/workshop.png"
    },
    {
      id: 14,
      category: "Music",
      status: "Paid",
      description: "Immerse yourself in the rich culture of classical music at our Indian Classical Concert. Experience mesmerizing performances by renowned classical musicians.",
      date: "8 Aug",
      day: "Thu",
      time: "7:30 PM - 10:30 PM",
      venue: "Cultural Center",
      location: "789 Raga Road",
      city: "Pimpri-Chinchwad",
      host: "Pimpri-Chinchwad Music Academy",
      title: "Indian Classical Concert",
      image: "Images/music.png"
    },
    {
      id: 15,
      category: "Art",
      status: "Free",
      description: "Join us for a live art demonstration by celebrated artists. Witness the creative process firsthand and gain insight into different art forms.",
      date: "12 Nov",
      day: "Tue",
      time: "10:00 AM - 1:00 PM",
      venue: "Art Gallery",
      location: "101 Brush Street",
      city: "Mumbai",
      host: "Mumbai Art Society",
      title: "Live Art Demonstration",
      image: "Images/art.png"
    },
    {
      id: 16,
      category: "Hobbies",
      status: "Free",
      description: "Embark on a thrilling adventure with our trekking expedition. Explore scenic trails, conquer challenging peaks, and experience the beauty of nature.",
      date: "17 Jul",
      day: "Wed",
      time: "6:00 AM - 5:00 PM",
      venue: "Trailhead",
      location: "456 Adventure Lane",
      city: "Pimpri-Chinchwad",
      host: "Pimpri-Chinchwad Adventure Club",
      title: "Trekking Expedition",
      image: "Images/hobbies.png"
    },
    {
      id: 17,
      category: "Food & Drink",
      status: "Paid",
      description: "Savor the flavors of authentic street food at our Food Truck Festival. Indulge in a variety of delicious dishes and culinary delights.",
      date: "22 Oct",
      day: "Tue",
      time: "5:00 PM - 9:00 PM",
      venue: "City Park",
      location: "789 Foodie Lane",
      city: "Chennai",
      host: "Chennai Food Truck Association",
      title: "Food Truck Festival",
      image: "Images/food&drink.png"
    }
  
  ,
  // Entry 18
  
    {
    id: 18,
    category: "Technology",
    status: "Paid",
    description: "Join us for a tech conference exploring the latest trends in artificial intelligence, blockchain, and cybersecurity. Gain insights from industry experts and network with fellow professionals.",
    date: "28 Nov",
    day: "Sat",
    time: "9:00 AM - 6:00 PM",
    venue: "Tech Center",
    location: "101 Innovation Avenue",
    city: "Bangalore",
    host: "Bangalore Tech Summit",
    title: "Tech Conference",
    image: "Images/technology.png"
    },
    {
    id: 19,
    category: "Fitness",
    status: "Free",
    description: "Get ready to sweat it out at our fitness boot camp! Join us for a high-intensity workout session led by certified trainers and achieve your fitness goals.",
    date: "15 Dec",
    day: "Tue",
    time: "6:00 PM - 7:30 PM",
    venue: "Fitness Center",
    location: "456 Health Street",
    city: "Delhi",
    host: "Delhi Fitness Club",
    title: "Fitness Boot Camp",
    image: "Images/fitness.png"
    },
    {
    id: 20,
    category: "Education",
    status: "Free",
    description: "Empower yourself with valuable knowledge and skills at our educational workshop. Learn from industry experts and enhance your professional development.",
    date: "10 Jan",
    day: "Mon",
    time: "10:00 AM - 12:00 PM",
    venue: "Learning Center",
    location: "789 Education Avenue",
    city: "Mumbai",
    host: "Mumbai Learning Institute",
    title: "Educational Workshop",
    image: "Images/education.png"
    },
    {
    id: 21,
    category: "Fashion",
    status: "Paid",
    description: "Experience the glitz and glamour of the fashion world at our runway show. Be dazzled by the latest fashion trends showcased by top designers.",
    date: "5 Feb",
    day: "Thu",
    time: "7:00 PM - 10:00 PM",
    venue: "Fashion Center",
    location: "101 Style Street",
    city: "Chennai",
    host: "Chennai Fashion Week",
    title: "Runway Show",
    image: "Images/fashion.png"
    },
    {
    id: 22,
    category: "Health",
    status: "Free",
    description: "Take charge of your health and well-being with our wellness seminar. Learn practical tips for maintaining a healthy lifestyle and preventing diseases.",
    date: "20 Mar",
    day: "Fri",
    time: "3:00 PM - 5:00 PM",
    venue: "Wellness Center",
    location: "456 Wellness Lane",
    city: "Hyderabad",
    host: "Hyderabad Health Foundation",
    title: "Wellness Seminar",
    image: "Images/health.png"
    },
    {
    id: 23,
    category: "Entertainment",
    status: "Paid",
    description: "Step into the world of magic and illusion at our mesmerizing magic show. Prepare to be amazed by mind-bending tricks and breathtaking performances.",
    date: "12 Apr",
    day: "Sun",
    time: "2:00 PM - 4:00 PM",
    venue: "Magic Theater",
    location: "789 Enchantment Avenue",
    city: "Pimpri-Chinchwad",
    host: "Pimpri-Chinchwad Magic Society",
    title: "Magic Show",
    image: "Images/entertainment.png"
    },
    {
    id: 24,
    category: "Travel",
    status: "Paid",
    description: "Embark on a journey of discovery with our travel photography exhibition. Immerse yourself in stunning landscapes and vibrant cultures captured by talented photographers.",
    date: "8 May",
    day: "Thu",
    time: "10:00 AM - 6:00 PM",
    venue: "Travel Expo",
    location: "101 Adventure Road",
    city: "Goa",
    host: "Goa Travel Association",
    title: "Travel Photography Exhibition",
    image: "Images/travel.png"
    },
    {
    id: 25,
    category: "Technology",
    status: "Free",
    description: "Explore the world of virtual reality at our VR showcase. Experience immersive simulations and cutting-edge technology in a fun and interactive environment.",
    date: "22 Jun",
    day: "Mon",
    time: "11:00 AM - 3:00 PM",
    venue: "Tech Hub",
    location: "456 Virtual Avenue",
    city: "Pune",
    host: "Pune VR Club",
    title: "VR Showcase",
    image: "Images/technology.png"
    },
    {
    id: 26,
    category: "Fitness",
    status: "Paid",
    description: "Challenge yourself with our extreme fitness challenge. Push your limits and conquer obstacles in this adrenaline-pumping fitness event.",
    date: "18 Jul",
    day: "Sat",
    time: "8:00 AM - 12:00 PM",
    venue: "Fitness Arena",
    location: "789 Endurance Street",
    city: "Mumbai",
    host: "Mumbai Fitness Challenge",
    title: "Extreme Fitness Challenge",
    image: "Images/fitness.png"
    },
    {
    id: 27,
    category: "Education",
    status: "Paid",
    description: "Enhance your skills with our coding boot camp. Learn programming languages and development tools from industry professionals and kickstart your tech career.",
    date: "10 Aug",
    day: "Sun",
    time: "9:00 AM - 4:00 PM",
    venue: "Coding Academy",
    location: "101 Code Street",
    city: "Bangalore",
    host: "Bangalore Code Institute",
    title: "Coding Boot Camp",
    image: "Images/education.png"
    },
    {
    id: 28,
    category: "Fashion",
    status: "Free",
    description: "Celebrate diversity and inclusivity at our fashion inclusivity workshop. Explore fashion as a form of self-expression and break free from stereotypes.",
    date: "5 Sep",
    day: "Sat",
    time: "2:00 PM - 5:00 PM",
    venue: "Fashion Studio",
    location: "456 Diversity Lane",
    city: "Pimpri-Chinchwad",
    host: "Pimpri-Chinchwad Fashion Alliance",
    title: "Fashion Inclusivity Workshop",
    image: "Images/fashion.png"
    },
    {
    id: 29,
    category: "Health",
    status: "Paid",
    description: "Discover the power of mindfulness at our meditation retreat. Recharge your mind, body, and soul in a serene and tranquil environment.",
    date: "20 Oct",
    day: "Tue",
    time: "8:00 AM - 5:00 PM",
    venue: "Meditation Center",
    location: "789 Serenity Avenue",
    city: "Hyderabad",
    host: "Hyderabad Mindfulness Center",
    title: "Meditation Retreat",
    image: "Images/health.png"
    },
    {
    id: 30,
    category: "Entertainment",
    status: "Paid",
    description: "Immerse yourself in the world of cinema at our film festival. Experience a curated selection of films from diverse genres and cultures.",
    date: "12 Nov",
    day: "Thu",
    time: "6:00 PM - 11:00 PM",
    venue: "Cinema Hall",
    location: "101 Film Street",
    city: "Goa",
    host: "Goa Film Society",
    title: "Film Festival",
    image: "Images/entertainment.png"
    },
    {
    id: 31,
    category: "Travel",
    status: "Free",
    description: "Escape to paradise with our beach yoga retreat. Relax on sandy shores, rejuvenate with yoga sessions, and immerse yourself in the beauty of nature.",
    date: "8 Dec",
    day: "Mon",
    time: "7:00 AM - 4:00 PM",
    venue: "Beach Resort",
    location: "456 Sunshine Lane",
    city: "Mumbai",
    host: "Mumbai Yoga Retreat",
    title: "Beach Yoga Retreat",
    image: "Images/travel.png"
    },
    {
    id: 32,
    category: "Technology",
    status: "Paid",
    description: "Stay ahead of the curve with our AI and machine learning workshop. Explore advanced algorithms and applications in this hands-on learning experience.",
    date: "15 Jan",
    day: "Wed",
    time: "10:00 AM - 3:00 PM",
    venue: "Tech Hub",
    location: "789 Innovation Avenue",
    city: "Bangalore",
    host: "Bangalore AI Institute",
    title: "AI & Machine Learning Workshop",
    image: "Images/technology.png"
    },
    {
    id: 33,
    category: "Fitness",
    status: "Free",
    description: "Join us for a community fitness challenge and inspire others to lead a healthy lifestyle. Participate in group workouts and achieve your fitness goals together.",
    date: "20 Feb",
    day: "Thu",
    time: "6:30 PM - 8:00 PM",
    venue: "Fitness Park",
    location: "101 Wellness Street",
    city: "Delhi",
    host: "Delhi Fitness Community",
    title: "Community Fitness Challenge",
    image: "Images/fitness.png"
    },
    {
    id: 34,
    category: "Education",
    status: "Paid",
    description: "Unlock your creative potential with our graphic design masterclass. Learn design principles, software techniques, and create stunning visual compositions.",
    date: "18 Mar",
    day: "Wed",
    time: "2:00 PM - 5:00 PM",
    venue: "Design Studio",
    location: "456 Creativity Lane",
    city: "Pimpri-Chinchwad",
    host: "Pimpri-Chinchwad Design Academy",
    title: "Graphic Design Masterclass",
    image: "Images/education.png"
    },
    {
    id: 35,
    category: "Fashion",
    status: "Paid",
    description: "Experience the magic of couture at our fashion gala. Witness exquisite designs and glamorous runway presentations by top fashion designers.",
    date: "12 Apr",
    day: "Sun",
    time: "7:00 PM - 11:00 PM",
    venue: "Fashion Center",
    location: "789 Glamour Avenue",
    city: "Hyderabad",
    host: "Hyderabad Fashion Guild",
    title: "Fashion Gala",
    image: "Images/fashion.png"
    },
    {
    id: 36,
    category: "Health",
    status: "Free",
    description: "Join our community wellness fair and discover holistic approaches to health and well-being. Enjoy free health screenings, fitness demos, and nutrition tips.",
    date: "8 May",
    day: "Thu",
    time: "9:00 AM - 2:00 PM",
    venue: "Wellness Park",
    location: "101 Harmony Street",
    city: "Goa",
    host: "Goa Wellness Initiative",
    title: "Community Wellness Fair",
    image: "Images/health.png"
    },
    {
    id: 37,
    category: "Entertainment",
    status: "Paid",
    description: "Dive into the world of literature at our book festival. Meet bestselling authors, attend book signings, and explore a diverse selection of books.",
    date: "22 Jun",
    day: "Mon",
    time: "10:00 AM - 4:00 PM",
    venue: "Book Fair",
    location: "456 Literary Lane",
    city: "Mumbai",
    host: "Mumbai Book Club",
    title: "Book Festival",
    image: "Images/entertainment.png"
    },
    {
    id: 38,
    category: "Travel",
    status: "Free",
    description: "Embark on a culinary journey at our food tour. Discover hidden gems and savor authentic local cuisine at renowned eateries.",
    date: "18 Jul",
    day: "Sat",
    time: "1:00 PM - 5:00 PM",
    venue: "Food Trail",
    location: "789 Culinary Avenue",
    city: "Delhi",
    host: "Delhi Food Tours",
    title: "Food Tour",
    image: "Images/travel.png"
    },
    {
    id: 39,
    category: "Technology",
    status: "Paid",
    description: "Explore the future of gaming at our virtual reality gaming expo. Experience cutting-edge VR games, demos, and interactive experiences.",
    date: "10 Aug",
    day: "Sun",
    time: "11:00 AM - 6:00 PM",
    venue: "Gaming Expo",
    location: "101 Gamer Street",
    city: "Bangalore",
    host: "Bangalore Gaming Association",
    title: "VR Gaming Expo",
    image: "Images/technology.png"
    },
    {
    id: 40,
    category: "Fitness",
    status: "Free",
    description: "Join our outdoor yoga session and connect with nature while practicing yoga. Find inner peace and balance in a serene outdoor environment.",
    date: "5 Sep",
    day: "Sat",
    time: "8:00 AM - 9:30 AM",
    venue: "Yoga Park",
    location: "456 Serenity Lane",
    city: "Pimpri-Chinchwad",
    host: "Pimpri-Chinchwad Yoga Society",
    title: "Outdoor Yoga Session",
    image: "Images/fitness.png"
    }
  ]
  


  export default Eventdata;
